### ISSUE TITLE
Add Summary Table to BOP Page

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/covid-19-behind-bars#499]
## Objective
Add summary table (same designs as state summary tables) to BOP page. 

## Answered Questions
> What will be the breakdown (columns and rows) be? Is the below breakdown (comment from Lane) adequate?

Yes, that summary table looks great! I think as long as it's clear that it's about Bureau of Prisons, which the page header would make clear I believe.

## Workflow Checklist
- [x] [UCLA] Provide feature requirements
- [x] [HO] Draft feature specification
- [x] [UCLA] Approve feature specification
- [x] [HO] Mockup designs and plan of approach
- [x] [UCLA] Feedback round (feedback on how closely designs match agreed upon feature spec) 
- [x] [HO] Implement design feedback
- [x] [UCLA] Approve designs
- [ ] [HO] Dev implementation demo (iterative) 
- [ ] [UCLA] Provide feedback (on ways in which dev implementation differs from designs and agreed upon functionality) 
- [ ] [HO] Final dev implementation demo
- [ ] [UCLA] Approve feature implementation for prod release

**Comment by Lane** [comment]
![image](https://user-images.githubusercontent.com/21034/129617825-7d24c394-0ff9-4076-b806-40358c703921.png)

**Comment by lizdewolf** [comment]
test

**Comment by lizdewolf** [comment]
Yes, that summary table looks great! I think as long as it's clear that it's about Bureau of Prisons, which the page header would make clear I believe.

**Comment by Lane** [comment]
# Specification

- the summary section will appear at the top of the page and replace the first two sections
- the visual presentation will match what is currently on the state level pages
  - under the page heading, there will be an intro paragraph, alongside a data score
  - there will be a total showing the nationwide aggregates for incarcerated people and staff in federal facilities
- all content within this section (intro paragraph, score labels + link, table headings and labels) can be edited via CMS

![image](https://user-images.githubusercontent.com/21034/130284112-7a527248-1dc6-42a4-98ac-d324b5946fc3.png)


# Implementation Tasks

- [ ] prepare data for the federal aggregates table (pictured above)

> pull from the [state_counts](https://github.com/uclalawcovid19behindbars/data/blob/master/latest-data/latest_state_counts.csv) file for the row where State == Federal (and the denominator for the rates would be Staff.Population and Residents.Population)

- [ ] create a component (or refactor the existing summary component for state pages) to display aggregate data for federal facilities, matching the screenshot above

- [ ] add entries so that text within this section can be edited via CMS

- [ ] test editing the content via CMS to ensure it works as intended
