### ISSUE TITLE
Add Search Functionality 

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/covid-19-behind-bars#504]
## Objective
Users should be able to search content on the UCLA CBB site. Site page content, Blog post/internal reports (match on title and description) will be discoverable 

## Workflow Checklist
- [x] [UCLA] Provide feature requirements
- [x] [HO] Draft feature specification
- [x] [UCLA] Approve feature specification
- [x] [HO] Mockup designs and plan of approach
- [x] [UCLA] Feedback round (feedback on how closely designs match agreed upon feature spec) 
- [x] [HO] Implement design feedback
- [x] [UCLA] Approve designs
- [ ] [HO] Dev implementation demo (iterative) 
- [ ] [UCLA] Provide feedback (on ways in which dev implementation differs from designs and agreed upon functionality) 
- [ ] [HO] Final dev implementation demo
- [ ] [UCLA] Approve feature implementation for prod release

**Comment by lizdewolf** [comment]
let's go with title/description only!

**Comment by Lane** [comment]
# Design Tasks

- [ ] search bar placement (global on site)
- [ ] determine search results design approach (e.g. autosuggest + separate page for , or search overlay)
  - example: [autosuggest + separate page for results](https://react-query.tanstack.com/overview)
  - example: [search overlay](https://react-query.tanstack.com/overview)
- [ ] include hover / focus states for inputs and search suggestions

# Implementation Tasks

- [ ] add client side search to gatsby site (see [Adding Search](https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-search/))
  - [ ] search should index page titles, meta descriptions, meta keywords, and summaries for blogs + reports
- [ ] implement search input as shown in designs
- [ ] implement search results as shown in designs
- [ ] verify keyboard navigation works
- [ ] verify accessible via screen reader

**Comment by ekmason** [comment]
## To be addressed: 
- What width should be used when switching between layouts? 
- Consider dismissal vs. clear text actions

**Comment by ekmason** [comment]
Client approved designs can be found [here](https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA-CBB-Style-guide-Site-map?node-id=2501%3A1121)

**Comment by ekmason** [comment]
## Component Breakdown

### Search Header Button (toggle)
- text pre-post search 
- mobile has no text if not active

### Search Input
- Placeholder Text w/o input
- X Shows up, clicking X clears textbox
- Input has on_change property
- Input should have focus state (for accessibility); refer to email subscription (border)

## Search Container Component
- input, toggle (mobile), summary and list of result components
- list of search result components (empty if no results)
- handle logic for updating results based on input changes
- desktop: overlay the page with the exception of the header
- mobile: overlay the page (entire page + header)
- mobile: include search toggle
- scrollable. when results exceed height of the container, you can scroll (departure from designs) 

## Search Summary Component
- should display # results ("showing __ results for {input}")
- If no text entered.... "no results for {input}"

## Search Result Component 
- on hover or focus, highlight entire row, show arrow
- entire row should be clickable, implement as a block link! 
- highlight all keyword matches (title and description) 
- truncate descriptions for mobile view after 80 characters

**Comment by Lane** [comment]
# Implementation Recommendations

Implementation could follow 3 steps:

## 1. Create search index

This is ready to go in #519.  A static file containing searchable content is generated on build and put in the public folder.  It will be accessibile at `{{SiteURL}}/search-1.json` (e.g. https://uclacovidbehindbars.org/search-1.json)

## 2. Create hook to provide search functionality

This hook would be responsible for loading the search JSON file, building a search engine with the data, and returning a function that accepts a query string and returns a list of results that match.

For data loading, [react-query](https://react-query.tanstack.com/) would be a good option, as it provides built-in caching, loading status, error status, etc.

For the search index, [js-search](https://github.com/bvaughn/js-search) would be a good option because you can easily add the search entries and attributes to search.  The hook would return the search function provided by js-search.

## 3. Create the front end components (see breakdown above)

The `SearchContainer` component could initialize the `useSearch` hook, and handle retrieving and displaying search results based on what is entered in the `SearchInput` component.  The `SearchInput`, `SearchResult`, and `SearchSummary` components would not require any state and could be strictly presentational components that render based on the provided props.
