### ISSUE TITLE
facility tooltip adjustments

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#75]
some adjustments to make to the facility level tooltips on state pages:

- [ ] use a [voronoi layer](https://www.visualcinnamon.com/2015/07/voronoi.html) for mouse events so that tooltips activate in nearby areas instead of when the mouse is directly over a point
- [x] display all relative stats in tooltip (see figma mockup)
- [x] order the spikes by size so that smaller spikes are layered on top of larger spikes, allowing them to be hovered

**Comment by hoshmn** [comment]
@Lane I'm wondering how sure we are that a voronoi grid is the optimal solution, considering both the work required and UX outcome. At its simplest, the grid would use a single point for each spike. If you used the spike's lat/lng coord, you'd have many cases where a user hovers the spike of point A but because they're technically closer to point B (point A being way below at the base of the spike) point B gets the hover. To improve upon this, you could instead make the grid based on the _center_ of each spike, but you might find you need to add additional points (like one for each of the 3 "vertices" of the spike) to get a more intuitive UX, and in some cases it would probably still cause some surprises. (That's a sweet tutorial you linked to, though, and I would enjoy the experiment if we do want to go that route!)

To test an alternative, I added some [simple logic](https://github.com/Hyperobjekt/covid-19-behind-bars/pull/104/files) to plot a second, transparent spike with a thicker stroke on top of each spike, essentially creating a buffer around each spike that makes it easier to hover. Wondering if that, combined with having the smaller spikes on top, will be enough -- @james-minton those are both implemented on the above branch if you want to try it out? It's not perfect, but sort of feels like no matter what it's going to be tough to reach certain spikes in dense areas.

**Comment by Lane** [comment]
@hoshmn yep, agree voronoi would be a better approach for point based data, might not work so well for the spikes.

i am open to any solution that provides a decent UX / implementation balance.  padding spikes might work, just very aware that the current implementation requires a high level of precision to hover over spikes that could cause issues for some.

[datawrapper](https://blog.datawrapper.de/spikemaps/) spike maps have a good implementation of this.  doesn't look like they are using voronoi, seems like they might be drawing a circle with a radius equal to the height of the spike for their hover area?

**Comment by hoshmn** [comment]
Interesting approach, yeah that's what it feels like they're doing. Funny how you can trigger the hover of a tall spike even when there's a shorter one between it and your cursor :) but it does seem effective, given that the smaller ones are on top. I'll give that approach a try if it feels like padding isn't enough.

**Comment by hoshmn** [comment]
I added the other stats to the tooltip. Experimenting with a couple of things:
- using the primary color to highlight the "selected" stat
- having the tooltip below so it doesn't obscure the spike as often. To the right could be better in that regard, but if it's going to run off the screen (which would be often) it'll appear above. Left isn't so good because the tooltip doesn't play nicely with the table.

<img width="934" alt="Screen Shot 2021-01-07 at 6 34 08 PM" src="https://user-images.githubusercontent.com/18331999/103956760-2f06bb00-5117-11eb-9013-45e4f314ac92.png">

**Comment by james-minton** [comment]
Merged and closing.

**Comment by hoshmn** [comment]
realized that these need test count/rate
cc @james-minton

**Comment by hoshmn** [comment]
on staging
